# Generated by Django 3.2.8 on 2021-10-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('user', models.CharField(max_length=25)),
                ('like', models.BooleanField()),
                ('dislike', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('user', models.CharField(max_length=25)),
            ],
        ),
    ]
