# Generated by Django 3.2.8 on 2021-10-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='date',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replies',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='videoID',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='replies',
            name='body',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='replies',
            name='commentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(),
        ),
    ]
