# Generated by Django 3.2.8 on 2021-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20211014_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='videoID',
            field=models.TextField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
